import type { MaskOptions } from "./types.js";

export const defaults: MaskOptions = {
  _maxTestPos: 500,
  placeholder: "_",
  optionalmarker: ["[", "]"],
  quantifiermarker: ["{", "}"],
  groupmarker: ["(", ")"],
  alternatormarker: "|",
  escapeChar: "\\",
  mask: null,
  regex: null,
  oncomplete: () => {},
  onincomplete: () => {},
  oncleared: () => {},
  repeat: 0,
  greedy: false,
  autoUnmask: false,
  removeMaskOnSubmit: false,
  clearMaskOnLostFocus: true,
  insertMode: true,
  insertModeVisual: true,
  clearIncomplete: false,
  alias: null,
  onKeyDown: () => {},
  onBeforeMask: null,
  onBeforePaste: null,
  onBeforeWrite: null,
  onUnMask: null,
  outputMask: null,
  showMaskOnFocus: true,
  showMaskOnHover: true,
  onKeyValidation: () => {},
  skipOptionalPartCharacter: " ",
  numericInput: false,
  rightAlign: false,
  undoOnEscape: true,
  radixPoint: "",
  _radixDance: false,
  groupSeparator: "",
  keepStatic: null,
  positionCaretOnTab: true,
  tabThrough: false,
  supportsInputType: ["text", "tel", "url", "password", "search"],
  isComplete: null,
  preValidation: null,
  postValidation: null,
  staticDefinitionSymbol: undefined,
  jitMasking: false,
  nullable: true,
  noValuePatching: false,
  positionCaretOnClick: "lvp",
  casing: null,
  inputmode: "text",
  importDataAttributes: true,
  shiftPositions: true,
  usePrototypeDefinitions: true,
  validationEventTimeOut: 3000,
  substitutes: {},
};
